### ISSUE TITLE
Can't download tsubame when building with docker

### ISSUE THREAD

**Issue by SunnyWjw** [nbtk/traceroute#1]
Hi,When I use docker to build the project, I can't download tsubame. I try to modify the source image of pip, but still can't solve the problem.

How should I solve this problem？

But I downloaded it directly on my local machine, but it was OK, the command used on this machine:` pip3 install tsubame`.

The following are some configurations and scripts when I use docker to build the project。
requirements.txt:
```
flask==1.0.2
flask-cors
celery
gunicorn
gevent
tsubame
```

Dockerfile:
```
FROM python:3.6
WORKDIR /Project/PingMonitor

COPY requirements.txt ./
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt -i https://pypi.org/simple

COPY . .
ENV LANG C.UTF-8
CMD ["gunicorn", "manage:app", "-c", "./gunicorn.conf.py"]
```

This is my compilation result：
<img width="912" alt="image" src="https://user-images.githubusercontent.com/11763317/196126111-3c6ff367-6e16-4017-a38d-a4c2128f8323.png">

**Comment by nbtk** [comment]
Hi SunnyWjw,

Thank you for your report!

I guess your docker's Python version is 3.6, but this module requires 3.7 or higher.
https://github.com/nbtk/tsubame/blob/b75652d9dd72590a444882c1874b0328d589afcb/setup.py#L24

However, 3.7 is just a tested version, so it might be able to run on 3.6. Fortunately, this module does not depend on any other modules. Therefor you can try copying the following script into your project and importing it directory.
https://github.com/nbtk/tsubame/blob/master/tsubame/traceroute.py

Happy Hacking 👍

**Comment by nbtk** [comment]
By the way, I am not sure if Docker containers can transmit and receive ICMP packets. This may be the biggest challenge.
